CREATE TABLE catalogservice.book (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   creation_date TIMESTAMP WITHOUT TIME ZONE,
   update_date TIMESTAMP WITHOUT TIME ZONE,
   title VARCHAR(255),
   original_title VARCHAR(255),
   isbn VARCHAR(255),
   release_date VARCHAR(255),
   edition_date VARCHAR(255),
   genre VARCHAR(255),
   edition VARCHAR(255),
   series BOOLEAN,
   synopsis VARCHAR(255),
   price DOUBLE PRECISION,
   promotional_price DOUBLE PRECISION,
   collection VARCHAR(255),
   category VARCHAR(255),
   availability VARCHAR(255),
   format VARCHAR(255),
   stock_available INTEGER NOT NULL,
   weight DOUBLE PRECISION,
   CONSTRAINT pk_book PRIMARY KEY (id)
);

CREATE TABLE catalogservice.author (
    id INT2 NOT NULL PRIMARY KEY,
    isni VARCHAR(512),
    name VARCHAR(512),
    original_full_name VARCHAR(512),
    date_of_birth VARCHAR(10),
    place_of_birth VARCHAR(256),
    date_of_death VARCHAR(10),
    place_of_death VARCHAR(256),
    about VARCHAR(1024)
);

CREATE TABLE catalogservice.book_sample (
    id INT2 NOT NULL PRIMARY KEY,
    book_id INT2 NOT NULL,
    sample VARCHAR(1024)
);

CREATE TABLE catalogservice.language (
    id INT2 NOT NULL PRIMARY KEY,
    code VARCHAR(10) NOT NULL
);

CREATE TABLE catalogservice.tag (
    id INT2 NOT NULL PRIMARY KEY,
    value VARCHAR(50) NOT NULL
);

CREATE TABLE catalogservice.publisher (
  id INTEGER NOT NULL PRIMARY KEY,
   creation_date TIMESTAMP WITHOUT TIME ZONE,
   update_date TIMESTAMP WITHOUT TIME ZONE,
   name VARCHAR(255),
   email VARCHAR(255),
   phone_number VARCHAR(255)
);