version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "172.25.141.121:5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_MULTIPLE_DATABASES: catalogservice, keycloak, notificationservice, orderservice, paymentservice, returnservice, shippingservice, stockservice, userservice
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "catalog" ]
      interval: 30s
      timeout: 60s
      retries: 5

    volumes:
      - ./utils/postgres/multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
    networks:
      - bookstore-network

  catalog-service:
    image: 'catalog-service:latest'
    build:
      context: ./CatalogService
      dockerfile: Dockerfile
    restart: always
    container_name: catalog-service
    ports:
      - "10000:10000"
      - "8081:8081"
    environment:
      - POSTGRES_HOST=catalogservice
      - POSTGRES_USER=postgres
      - SPRINGPROFILES=dev,actuator
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:10000/actuator/health | grep UP || exit 1"
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./CatalogService/log:/CatalogService/log
    networks:
      - bookstore-network

  stock-service:
    image: 'stock-service:latest'
    build:
      context: ./StockService
      dockerfile: Dockerfile
    restart: always
    container_name: stock-service
    ports:
      - "10001:10001"
      - "8082:8082"
    environment:
      - POSTGRES_HOST=stockservice
      - POSTGRES_USER=postgres
      - SPRINGPROFILES=dev,actuator
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      keycloak:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:10001/actuator/health | grep UP || exit 1"
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - ./StockService/log:/StockService/log
    networks:
      - bookstore-network

  notification-service:
    image: 'notification-service:latest'
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    restart: always
    container_name: notification-service
    ports:
      - "10002:10002"
      - "8083:8083" #debug
      - "8000:8000"  #jobrnr dashboard
    environment:
      - POSTGRES_HOST=notificationservice
      - POSTGRES_USER=postgres
      - SPRINGPROFILES=dev,actuator
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:10002/actuator/health | grep UP || exit 1"
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - ./NotificationService/log:/NotificationService/log
    networks:
      - bookstore-network

  order-service:
    image: 'order-service:latest'
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    restart: always
    container_name: order-service
    ports:
      - "10003:10003"
      - "8084:8084" #debug
    environment:
      - POSTGRES_HOST=orderservice
      - POSTGRES_USER=postgres
      - SPRINGPROFILES=dev,actuator
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:10003/actuator/health | grep UP || exit 1"
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - ./OrderService/log:/OrderService/log
    networks:
      - bookstore-network

  payment-service:
    image: 'payment-service:latest'
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
    restart: always
    container_name: payment-service
    ports:
      - "10004:10004"
      - "8085:8085" #debug
    environment:
      - POSTGRES_HOST=paymentservice
      - POSTGRES_USER=postgres
      - SPRINGPROFILES=dev,actuator
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:10004/actuator/health | grep UP || exit 1"
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - ./PaymentService/log:/PaymentService/log
    networks:
      - bookstore-network

  return-service:
    image: 'return-service:latest'
    build:
      context: ./ReturnService
      dockerfile: Dockerfile
    restart: always
    container_name: return-service
    ports:
      - "10005:10005"
      - "8086:8086" #debug
    environment:
      - POSTGRES_HOST=returnservice
      - POSTGRES_USER=postgres
      - SPRINGPROFILES=dev,actuator
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:10005/actuator/health | grep UP || exit 1"
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - ./ReturnService/log:/ReturnService/log
    networks:
      - bookstore-network

  shipping-service:
    image: 'shipping-service:latest'
    build:
      context: ./ShippingService
      dockerfile: Dockerfile
    restart: always
    container_name: shipping-service
    ports:
      - "10006:10006"
      - "8087:8087" #debug
    environment:
      - POSTGRES_HOST=shippingservice
      - POSTGRES_USER=postgres
      - SPRINGPROFILES=dev,actuator
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:10006/actuator/health | grep UP || exit 1"
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - ./ShippingService/log:/ShippingService/log
    networks:
      - bookstore-network

  user-service:
    image: 'user-service:latest'
    build:
      context: ./UserService
      dockerfile: Dockerfile
    restart: always
    container_name: user-service
    ports:
      - "10007:10007"
      - "8088:8088" #debug
    environment:
      - POSTGRES_HOST=user-service
      - POSTGRES_USER=postgres
      - SPRINGPROFILES=dev,actuator
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:10007/actuator/health | grep UP || exit 1"
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - ./UserService/log:/UserService/log
    networks:
      - bookstore-network

  dummy-ctt:
    image: 'dummy-ctt:latest'
    build:
      context: ./DummyCtt
      dockerfile: Dockerfile
    restart: always
    container_name: dummy-ctt
    ports:
      - "10008:10008"
      - "8089:8089" #debug
    environment:
      - SPRINGPROFILES=dev,actuator
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:10008/actuator/health | grep UP || exit 1"
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - ./DummyCtt/log:/DummyCtt/log
    networks:
      - bookstore-network

  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.13.0-rc.5-management'
    ports:
      # The standard AMQP protocol port
      - '172.25.141.121:5672:5672'
      # HTTP management UI
      - '15672:15672' #Management Port - default user:pass = guest:guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - bookstore-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.7
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    command: -v start-dev --import-realm
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3" ]
      interval: 20s
      timeout: 60s
      retries: 5
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./utils/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - bookstore-network

networks:
  bookstore-network: