CREATE TABLE orderservice."order" (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   creation_date TIMESTAMP WITHOUT TIME ZONE,
   update_date TIMESTAMP WITHOUT TIME ZONE,
   customer_id INTEGER,
   shipment_date TIMESTAMP WITHOUT TIME ZONE,
   total_price_items DOUBLE PRECISION,
   total_weight DOUBLE PRECISION,
   tax DOUBLE PRECISION,
   total_price_order DOUBLE PRECISION,
   status VARCHAR(255),
   editable BOOLEAN,
   CONSTRAINT pk_order PRIMARY KEY (id)
);

CREATE TABLE orderservice.item (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   creation_date TIMESTAMP WITHOUT TIME ZONE,
   update_date TIMESTAMP WITHOUT TIME ZONE,
   order_id INTEGER,
   book_id INTEGER,
   quantity INTEGER,
   unit_price DOUBLE PRECISION,
   unit_weight DOUBLE PRECISION,
   CONSTRAINT pk_item PRIMARY KEY (id)
);

ALTER TABLE orderservice.item ADD CONSTRAINT FK_ITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES orderservice."order" (id);