server:
  port: 10004
management:
  server:
    port: 10004

#database
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        default-schema: paymentservice
  datasource:
    url: jdbc:postgresql://postgres:5432/paymentservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

#logs
logging:
  file:
    path: PaymentService/log
    name: ${logging.file.path}/basePayment-service.log

paypal:
  mode: sandbox
  client:
    id: ATYEyFvYXHED6NCgIl-mNLumgEM2egOsKVnBTow3E35KTaTWB3hROjY1ZuevYI7XrCV_qRNTnxS90vBl
    secret: EF4naVXxM6Fyk7yzNCZedymVXhGw2VLs9AbjquvtZXw60clk54q_24k4QP2IJj-aBBr-T8WlYuysovOn
  
bookstore:
  merchantId: bookstore