CREATE TABLE paymentservice.payment (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   creation_date TIMESTAMP WITHOUT TIME ZONE,
   update_date TIMESTAMP WITHOUT TIME ZONE,
   order_id INTEGER,
   customer_id INTEGER,
   return_id INTEGER,
   payment_method VARCHAR(255),
   payment_status VARCHAR(255),
   operation_date TIMESTAMP WITHOUT TIME ZONE,
   amount DOUBLE PRECISION,
   payment_details JSONB,
   CONSTRAINT pk_payment PRIMARY KEY (id)
);