CREATE TABLE paymentservice.payment (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   order_id INTEGER,
   customer_id INTEGER,
   payment_method VARCHAR(255),
   payment_status VARCHAR(255),
   payment_date TIMESTAMP WITHOUT TIME ZONE,
   payment_amount DOUBLE PRECISION,
   CONSTRAINT pk_payment PRIMARY KEY (id)
);