CREATE TABLE shippingservice.shipment (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   order_id INTEGER,
   date TIMESTAMP WITHOUT TIME ZONE,
   tracking_number VARCHAR(255),
   shipment_method VARCHAR(255),
   CONSTRAINT pk_shipment PRIMARY KEY (id)
);