CREATE TABLE returnservice.return (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   creation_date TIMESTAMP WITHOUT TIME ZONE,
   update_date TIMESTAMP WITHOUT TIME ZONE,
   order_id INTEGER,
   customer_id INTEGER,
   return_reason VARCHAR(255),
   return_status VARCHAR(255),
   amount_to_refund DOUBLE PRECISION,
   refund_type VARCHAR(255),
   tracking_code VARCHAR(255),
   external_payment_id VARCHAR(255),
   CONSTRAINT pk_return PRIMARY KEY (id)
);